default:

# proxmox-ubuntu-20-04:
# 	sh ./scripts/ubuntu-20.04.sh
#	sh ./scripts/cleanup.sh ./packer/ubuntu-20.04

proxmox-ubuntu-22-04:
	sh ./scripts/ubuntu-22.04.sh
	sh ./scripts/cleanup.sh ./packer


clean:
	sh ./scripts/cleanup.sh ./packer